version: '3.8'
services:
  php:
    container_name: php
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8000:8000
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
      - ./vendor:/var/www/app/vendor
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
